language: cpp
compiler:
  - gcc
sudo: required
dist: trusty
cache: apt
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5
      - cppcheck
install:
  - mkdir build && cd build
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - git clone https://github.com/simonkrogmann/utilgpu.git
  - cd utilgpu && mkdir build && cd build && cmake .. -DCLANG_FORMAT=OFF
  - make && sudo make install
  - cd ../..
before_script:
  - cppcheck ../source
script:
  - cmake .. && make && make test
