language: cpp
compiler:
  - gcc
sudo: required
dist: trusty
cache: apt
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5
      - qtbase5-dev
      - cppcheck
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
before_script:
  - cppcheck source
